configuration_system:
  host_name: "{{ inventory_hostname }}"

  domain_name: "dmz.home"
  domain_search: "dmz.home"

  login:
    user:
      # ### USERNAMES
      - name: automation
        authentication:
          encrypted_password: $6$ZlA2peEY$803k5QuDxH1YBoHBVObfr0KVLavXLTu8nUlzIUmJbIhrMcQZZ3dWLD7Jj.IK0RKFXMJ6Csf2pnxg8MiuppZHj1
        class: super-user
        uid: "3001"

  name_server:
    - name: 192.168.101.11
    - name: 192.168.101.12

  root_authentication:
    encrypted_password: $6$eG4FXiQW$J4/a.5GZlXlrKcvJTpbaMl.qIelPqjR5lFk.POmxo5O3Vp5OdjHFFJ97PMqvABuZZOGXrdvSE6YF3f33wilgO.

  services:
    netconf:
      ssh: null
    rest:
      enable_explorer: null
      http:
        port: "8080"
    ssh:
      root_login: allow

  syslog:
    file:
      # ### SYSLOG MESSAGES FILE "show log messages"
      - name: messages
        contents:
          - name: any
            notice: null
          - name: authorization
            info: null

      # ### SYSLOG COMMAND HISTORY FILE "show log interactive-commands"
      - name: interactive-commands
        contents:
          any: null
          name: interactive-commands

      # ### SYSLOG LOG DEFAULT MESSAGES (structured data format) "show log default-log-messages"
      - name: default-log-messages
        match: "(requested 'commit' operation)|(requested 'commit synchronize' operation)|(copying configuration to juniper.save)|(commit complete)|ifAdminStatus|(FRU power)|(FRU removal)|(FRU insertion)|(link UP)|transitioned|Transferred|transfer-file|(license add)|(license delete)|(package -X update)|(package -X delete)|(FRU Online)|(FRU Offline)|(plugged in)|(unplugged)|GRES"
        contents:
          info: null
          name: any
        structured_data: null

    # ### SYSLOG SERVERS
    host:
      - name: 192.168.103.31
        contents:
          any: null
          name: any
        port: 5514
        source_address: "{{ ansible_host }}"
        structured_data: null

    user:
      contents:
        emergency: null
        name: any
      name: "*"
      # match: "!(.*Scheduler Oinker*.|.*Frame 0*.|.*ms without yielding*.)"
  time_zone: America/Chicago
