site_name: Juniper PyEZ L3VPN MPLS
site_description: "Build and deploy a full MPLS network on vMX routers."
site_url: "https://cdot65.github.io/juniper-mpls-l3vpn-demo/"
repo_name: "cdot65/juniper-mpls-l3vpn-demo"
repo_url: "https://github.com/cdot65/juniper-mpls-l3vpn-demo"
edit_uri: "edit/mainline/site/content"
copyright: "Copyright &copy; 2022 cdot65"
docs_dir: "site/content"
site_dir: "docs"
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
    - name: English
      link: ./en/
      lang: en

nav:
  - Home: index.md
  - Documentation:
      - Overview: docs/overview.md
      - Lab Environment:
          - Juniper vLabs: docs/lab-environment/juniper-vlabs.md
          - Local: docs/lab-environment/local.md
      - Automation:
          - Overview: docs/automation/overview.md
          - Scripts:
              - configure: docs/automation/configure.md
              - generate: docs/automation/generate.md
              - rollback: docs/automation/rollback.md
          - Tools: docs/automation/tools.md
      - Network:
          - Overview: docs/network/overview.md
          - IP Schema: docs/network/ip.md
          - MPLS: docs/network/mpls.md
          - Routing: docs/network/routing.md
      - Validation: docs/validate.md

theme:
  name: material
  custom_dir: site/overrides
  palette:
    primary: white
  font: false
  icon:
    logo: octicons/terminal-16
  favicon: assets/images/cli.png
  language: en
  features:
    - tabs
    - instant

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - site/overrides/.icons

plugins:
  - search
  - redirects:
      redirect_maps:
        "docs/juniper-vlabs.md": "docs/lab-environment/juniper-vlabs.md"
        "docs/locally.md": "docs/lab-environment/local.md"
  - macros:
      include_dir: site/content/docs/include
