configuration:
  '@commit_localtime': 2021-03-22 21:17:45 UTC
  '@commit_seconds': '1616447865'
  '@commit_user': automation
  interfaces:
    interface:
    - name: ge-0/0/0
      unit:
        family:
          inet:
            address:
              name: 10.1.2.1/24
          iso: null
          mpls: null
        name: '0'
    - name: ge-0/0/1
      unit:
        family:
          inet:
            address:
              name: 10.1.11.1/24
          iso: null
          mpls: null
        name: '0'
    - name: ge-0/0/3
      unit:
        family:
          inet:
            address:
              name: 10.1.13.1/24
          iso: null
          mpls: null
        name: '0'
    - disable: null
      name: ge-0/0/5
    - disable: null
      name: ge-0/0/6
    - disable: null
      name: ge-0/0/7
    - disable: null
      name: ge-0/0/8
    - disable: null
      name: ge-0/0/9
    - name: fxp0
      unit:
        family:
          inet:
            address:
              name: 192.168.105.20/24
        name: '0'
    - name: lo0
      unit:
        family:
          inet:
            address:
              name: 192.168.255.1/32
          iso:
            address:
              name: 49.0001.0192.0168.0255.0001.00
        name: '0'
  protocols:
    isis:
      interface:
      - name: ge-0/0/0.0
      - name: ge-0/0/1.0
      - name: ge-0/0/2.0
      - name: ge-0/0/3.0
      - name: ge-0/0/4.0
      - name: lo0.0
      level:
        disable: null
        name: '1'
    lldp:
      interface:
        name: all
    mpls:
      interface:
      - name: all
      - disable: null
        name: fxp0.0
    router_advertisement:
      interface:
        name: fxp0.0
    rsvp:
      interface:
      - name: ge-0/0/0.0
      - name: ge-0/0/1.0
      - name: ge-0/0/2.0
      - name: ge-0/0/3.0
      - name: ge-0/0/4.0
      - name: lo0.0
  routing_options:
    autonomous_system:
      as_number: '65000'
    router_id: 192.168.255.1
    static:
      route:
      - name: 192.168.101.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.102.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.103.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.104.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 10.9.0.0/16
        next_hop: 192.168.105.1
        no_readvertise: null
  security:
    certificates:
      local:
        certificate: '-----BEGIN PRIVATE KEY-----\nMIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAL1v6dBbS329wqup\nSd6M18HbdW7vDnxpiWsJGvZ6pjUdblB31vybm3ukAs0JTwv3APzJcY/LB40O7a4N\n9VNkHRQXUWO972hspLLa5uBZya3rVmE/42lHwgICVh8WfLKX476IftU538/izL0O\nUxhXTkr4Y8593wOMn9swZfgDhmOPAgMBAAECgYAlZRcpuyveyXvJOSTM2s6ohPLc\nkDIy2v52c5iv+SwgJgwltFJrESiTMqAe62yANyUpwXY6ZWC7NqwyhKzd5lBa1PVX\nwNo65eztqEMs4LzckAGQR3orLMSxBPKGujN06wuuqbw3/z00nOr0HhKVQxIsz31T\nQoRlv77vwNlXnfJjKQJBAOPJg6vb2JWeS/l5uD8NVqOHo6KT4Rg423CfPlaJ1Mko\nQvdBbvcyFKCAwW5BWU1u3thFmwTSlsBil3H0thBUm9UCQQDU5m3UVmlPKaIVRllm\nCPR1+JE6jwT4qms4vF2eZ2+3QGz0lDcx7w4mOdYgSHQ56OxM4E77SA+2FS8Cl1Im\nmqfTAkBEyaMAsChMrnwE/5P7Pnzub1SkEQJFvU3PSdeabI8cnBL09gabkb0W5ysC\nr6tXLecP6p0wrKOnv146pIqijdptAkBnQiO+uvJ0rLKqMualMG6w0RBPIJK+sJk0\neVfGvlBWxu6RaVmj5Fgufhq2qa2FcM07NAfapEbKf1e/n/j+NEB1AkEA12zKZa7h\nIcE1hL0h6ySmrihMmqRXvxOBXJl+vGcmbe86vmJKU6qVh4+SB0O9PwZufiKzQu31\nGHCyCVW0SMBy1A==\n-----END PRIVATE KEY-----\n-----BEGIN CERTIFICATE-----\nMIIDLjCCApegAwIBAgIUT4j0bbFJjazxH56EvoeyWJw/CDcwDQYJKoZIhvcNAQEL\nBQAwgagxCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVUZXhhczEQMA4GA1UEBwwHSG91\nc3RvbjEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMQswCQYDVQQL\nDAJJVDEeMBwGA1UEAwwVZGFsbGFzLWxlYWYxLmRtei5ob21lMScwJQYJKoZIhvcN\nAQkBFhhjcmVtc2J1cmdAcHJvdG9ubWFpbC5jb20wHhcNMjEwMzE3MjEyNjA0WhcN\nMjEwNDE2MjEyNjA0WjCBqDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVRleGFzMRAw\nDgYDVQQHDAdIb3VzdG9uMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBM\ndGQxCzAJBgNVBAsMAklUMR4wHAYDVQQDDBVkYWxsYXMtbGVhZjEuZG16LmhvbWUx\nJzAlBgkqhkiG9w0BCQEWGGNyZW1zYnVyZ0Bwcm90b25tYWlsLmNvbTCBnzANBgkq\nhkiG9w0BAQEFAAOBjQAwgYkCgYEAvW/p0FtLfb3Cq6lJ3ozXwdt1bu8OfGmJawka\n9nqmNR1uUHfW/Jube6QCzQlPC/cA/Mlxj8sHjQ7trg31U2QdFBdRY73vaGykstrm\n4FnJretWYT/jaUfCAgJWHxZ8spfjvoh+1Tnfz+LMvQ5TGFdOSvhjzn3fA4yf2zBl\n+AOGY48CAwEAAaNTMFEwHQYDVR0OBBYEFPAHxBuXuTP44vJhbUSl5vO8I2fSMB8G\nA1UdIwQYMBaAFPAHxBuXuTP44vJhbUSl5vO8I2fSMA8GA1UdEwEB/wQFMAMBAf8w\nDQYJKoZIhvcNAQELBQADgYEAdovrUzJTa7XlieorJRsY0S7ys5O31dCcFSPtcPXf\nTdaOI88Ofbin6hKz0f2yC6GdB3SBsOjClwT1Q//WW9WeeyoGhMkNmKNAL9KfVXwi\nM6xN0x04wjr3fBonFY97wDkqKcCJQXuH1a3Wx/kvlNPu8hApoiSR15nhShlV54pZ\nsGo=\n-----END
          CERTIFICATE-----\n'
        name: packetferret
  snmp:
    community:
      authorization: read-only
      clients:
        name: 0.0.0.0/0
      name: healthbot
    trap_group:
      categories:
        chassis: null
        routing: null
      name: SNMP_TRAP
      targets:
        name: 192.168.105.77
      version: v2
    trap_options:
      source_address:
        address: 192.168.105.20
  system:
    host_name: lonestar-p1
    login:
      user:
        authentication:
          encrypted_password: $6$Jiy/pkvx$N1pr19HpKfViBZ78ijP9vkmTIzpIz/2y2eaaYF8tau/I6PvALer.q.GM80YJA6UlrF6N4sNHrM4cRvsQBdksC.
        class: super-user
        name: automation
        uid: '2000'
    processes:
      dhcp_service:
        traceoptions:
          file:
            filename: dhcp_logfile
            size: 10m
          flag:
            name: packet
          level: all
    root_authentication:
      encrypted_password: $6$4VO4kprG$NXrpXGpL.x6Zy.9n4vvwmyjnY8UN5r3WgQuv9/J/7po/Q6k2d9UA.XHWZoNdrSgJLOVJLX38XvhQatqM4OwST1
    services:
      extension_service:
        notification:
          allow_clients:
            address: 0.0.0.0/0
        request_response:
          grpc:
            max_connections: '30'
            undocumented:
            - clear_text: null
            - skip_authentication: null
      netconf:
        ssh: null
      ssh:
        root_login: allow
    syslog:
      file:
      - contents:
        - name: any
          notice: null
        - info: null
          name: authorization
        name: messages
      - contents:
          any: null
          name: interactive-commands
        name: interactive-commands
      host:
        contents:
          any: null
          name: any
        name: 192.168.105.77
        port: '514'
        source_address: 192.168.105.20
        structured_data: null
      user:
        contents:
          emergency: null
          name: any
        name: '*'
  version: 20200609.165031.6_builder.r1115480
