lldp-neighbors-information:
    lldp-neighbor-information:
    -   lldp-local-parent-interface-name: '-'
        lldp-local-port-id: ge-0/0/4
        lldp-remote-chassis-id: 08:b2:58:a5:9c:a2
        lldp-remote-chassis-id-subtype: Mac address
        lldp-remote-port-description: ge-0/0/10
        lldp-remote-system-name: houston-sw0
    -   lldp-local-parent-interface-name: '-'
        lldp-local-port-id: ge-0/0/0
        lldp-remote-chassis-id: 28:a2:4b:80:14:50
        lldp-remote-chassis-id-subtype: Mac address
        lldp-remote-port-description: brew-oob
        lldp-remote-system-name: coruscant
    -   lldp-local-parent-interface-name: '-'
        lldp-local-port-id: ge-0/0/7
        lldp-remote-chassis-id: 30:7c:5e:3e:53:f0
        lldp-remote-chassis-id-subtype: Mac address
        lldp-remote-port-description: ge-0/1/2
        lldp-remote-system-name: colo-rt0.dmz.home
