configuration:
  '@commit_localtime': 2021-03-29 00:36:55 UTC
  '@commit_seconds': '1616978215'
  '@commit_user': root
  forwarding_options:
    storm_control_profiles:
      all: null
      name: default
  interfaces:
    interface:
    - description: '[xe-0/0/1] houston-spine1:xe-0/0/1'
      mtu: '9216'
      name: xe-0/0/1
      unit:
        family:
          inet:
            address:
              name: 172.16.1.3/31
          iso: null
        name: '0'
    - description: '[xe-0/0/2] houston-spine1:xe-0/0/2'
      mtu: '9216'
      name: xe-0/0/2
      unit:
        family:
          inet:
            address:
              name: 172.16.2.3/31
          iso: null
        name: '0'
    - description: '[xe-0/0/11] pc2:eth0'
      mtu: '9100'
      name: xe-0/0/11
      native_vlan_id: '100'
      unit:
        family:
          ethernet_switching:
            interface_mode: trunk
            vlan:
              members: V100_PC
        name: '0'
    - name: em0
      unit:
        family:
          inet:
            address:
              name: 192.168.105.44/24
        name: '0'
    - name: em1
      unit:
        family:
          inet:
            address:
              name: 169.254.0.2/24
        name: '0'
    - name: irb
      unit:
      - family:
          inet:
            address:
              name: 192.168.100.1/24
            mtu: '9000'
        mac: 00:1c:73:00:00:01
        name: '100'
      - family:
          inet:
            address:
              name: 192.168.200.1/24
            mtu: '9000'
        mac: 00:1c:73:00:00:01
        name: '200'
    - name: lo0
      unit:
      - family:
          inet:
            address:
              name: 10.255.1.12/32
          iso:
            address:
              name: 49.0001.0010.0255.0001.0012.00
        name: '0'
      - family:
          inet:
            address:
              name: 10.255.2.12/32
        name: '2'
  policy_options:
    policy_statement:
    - name: AllPodNetworks
      term:
        from:
          family: inet
          protocol: direct
        name: AllPodNetworks-10
        then:
          accept: null
    - name: BGP-AOS-Policy
      term:
        from:
          policy: AllPodNetworks
        name: BGP-AOS-Policy-10
        then:
          accept: null
    - name: DEFAULT_DENY
      term:
        name: DEFAULT_DENY-10
        then:
          reject: null
    - name: PFE-LB
      then:
        load_balance:
          per_packet: null
  protocols:
    bgp:
      graceful_restart: null
      group:
        multihop:
          no_nexthop_change: null
          ttl: '1'
        multipath:
          multiple_as: null
        name: l3clos-l-evpn
        neighbor:
        - description: houston-spine1-evpn-overlay
          family:
            evpn:
              signaling: null
          local_address: 10.255.1.12
          name: 10.255.1.1
          peer_as: '65002'
        - description: houston-spine2-evpn-overlay
          family:
            evpn:
              signaling: null
          local_address: 10.255.1.12
          name: 10.255.1.2
          peer_as: '65002'
        type: external
      log_updown: null
      multipath: null
    evpn:
      default_gateway: do-not-advertise
      encapsulation: vxlan
      extended_vni_list: all
      vni_options:
        vni:
        - name: '10100'
          vrf_target:
            community: target:10100:1
        - name: '10200'
          vrf_target:
            community: target:10200:1
    igmp_snooping:
      vlan:
        name: default
    isis:
      export: ( BGP-AOS-Policy || DEFAULT_DENY )
      interface:
      - hello_padding_type: disable
        name: xe-0/0/1.0
        point_to_point: null
      - hello_padding_type: disable
        name: xe-0/0/2.0
        point_to_point: null
      - name: lo0.0
        passive: null
      level:
      - disable: null
        name: '1'
      - name: '2'
        prefix_export_limit: '20000'
        wide_metrics_only: null
      lsp_lifetime: '65535'
      reference_bandwidth: 1000g
    lldp:
      interface:
        name: all
      neighbour_port_info_display: port-id
      port_description_type: interface-description
      port_id_subtype: interface-name
    rstp:
      bpdu_block_on_edge: null
      bridge_priority: '0'
      interface:
        name: xe-0/0/11
  routing_instances:
    instance:
      instance_type: vrf
      interface:
      - name: irb.100
      - name: irb.200
      - name: lo0.2
      name: HOUSTON_VRF
      protocols:
        evpn:
          ip_prefix_routes:
            advertise: direct-nexthop
            encapsulation: vxlan
            export: ( BGP-AOS-Policy || DEFAULT_DENY )
            vni: '10000'
      route_distinguisher:
        rd_type: 10.255.1.12:2
      routing_options:
        auto_export: null
        multipath: null
      vrf_table_label: null
      vrf_target:
        community: target:10000:1
  routing_options:
    autonomous_system:
      as_number: '65012'
    forwarding_table:
      chained_composite_next_hop:
        ingress:
          evpn: null
      ecmp_fast_reroute: null
      export: PFE-LB
    router_id: 10.255.1.12
    static:
      route:
      - name: 192.168.101.0/24
        next_hop: 192.168.105.1
      - name: 192.168.102.0/24
        next_hop: 192.168.105.1
      - name: 192.168.103.0/24
        next_hop: 192.168.105.1
      - name: 192.168.104.0/24
        next_hop: 192.168.105.1
      - name: 10.9.0.0/16
        next_hop: 192.168.105.1
  snmp:
    community:
      authorization: read-only
      clients:
        name: 0.0.0.0/0
      name: healthbot
    trap_group:
      categories:
        chassis: null
        routing: null
      name: SNMP_TRAP
      targets:
        name: 192.168.105.77
      version: v2
    trap_options:
      source_address:
        address: 192.168.105.20
  switch_options:
    route_distinguisher:
      rd_type: 10.255.1.12:65534
    vrf_target:
      community: target:100:100
    vtep_source_interface:
      interface_name: lo0.0
  system:
    extensions:
      providers:
      - license_type:
          deployment_scope: commercial
          name: juniper
        name: juniper
      - license_type:
          deployment_scope: commercial
          name: juniper
        name: chef
    host_name: houston-leaf2
    login:
      user:
      - authentication:
          encrypted_password: $6$g1go/Ek4$Ouepey186Xo0ZO6kDS8MdJHhFYVIKff7UifdrawiPhOPWlUtEJnGzpLRgEkQEmEvJl8vLvcVUtD3L2baO8ASg.
        class: super-user
        name: automation
        uid: '2001'
      - authentication:
          ssh_rsa:
            name: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
        class: super-user
        name: vagrant
        uid: '2000'
    root_authentication:
      encrypted_password: $6$W0N6t7fV$.B4uhCIFzP4JhPyohFJVR6Ntbsvpj3BL.glw81gwGqKcT2GsUli1AD1D1oWa6hn0sSWZpi/Y1E9GAU9f3kCqV/
      ssh_rsa:
        name: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
    services:
      extension_service:
        notification:
          allow_clients:
            address: 0.0.0.0/0
        request_response:
          grpc:
            max_connections: '30'
            undocumented:
            - clear_text: null
            - skip_authentication: null
      netconf:
        ssh: null
      rest:
        enable_explorer: null
        http:
          port: '8080'
      ssh:
        root_login: allow
    syslog:
      file:
      - contents:
        - name: any
          notice: null
        - info: null
          name: authorization
        name: messages
      - contents:
          any: null
          name: interactive-commands
        name: interactive-commands
      user:
        contents:
          emergency: null
          name: any
        name: '*'
  version: 20191212.201431_builder.r1074901
  vlans:
    vlan:
    - l3_interface: irb.100
      name: V100_PC
      vlan_id: '100'
      vxlan:
        vni: '10100'
    - l3_interface: irb.200
      name: V200_SERVER
      vlan_id: '200'
      vxlan:
        vni: '10200'
    - name: default
      vlan_id: '1'
