---
### ---------------------------------------------------------------------------
### VALIDATE THAT ANSIBLE CONTROL MACHINE IS RUNNING A RECENT ANSIBLE VERSION
### ---------------------------------------------------------------------------
- hosts: all
  connection: local
  gather_facts: False
  become: False
  roles: 
    # - cremsburg.junos-config-bootstrap
    - juniper.junos
  tasks:
    - name: "### APPLY CANDIDATE CONFIGURATION ON REMOTE DEVICE ###"
      juniper_junos_config:
        load: update
        user: "automation"
        passwd: "juniper123"
        # ssh_private_key_file: "{{ provider_info.ssh_private_key_file }}"
        src: "{{ completed_config_file }}"
        timeout: 240
      register: result
      # when: is_diff is defined

    - name: "### PRINT THE RESULT TO CONSOLE ###"
      debug:
        var: result.diff_lines
      when: result.diff_lines is defined