configuration:
  '@commit_localtime': 2021-03-21 21:00:28 UTC
  '@commit_seconds': '1616360428'
  '@commit_user': automation
  interfaces:
    interface:
    - name: ge-0/0/3
      unit:
        family:
          inet:
            address:
              name: 10.1.13.13/24
          iso: null
          mpls: null
        name: '0'
    - name: ge-0/0/4
      unit:
        family:
          inet:
            address:
              name: 10.2.13.13/24
          iso: null
          mpls: null
        name: '0'
    - name: ge-0/0/9
      unit:
        family:
          inet:
            address:
              name: 172.20.3.1/24
        name: '0'
    - name: fxp0
      unit:
        family:
          inet:
            address:
              name: 192.168.105.27/24
        name: '0'
    - name: lo0
      unit:
        family:
          inet:
            address:
              name: 192.168.255.13/32
          iso:
            address:
              name: 49.0001.0192.0168.0255.0013.00
        name: '0'
  policy_options:
    policy_statement:
      name: BGP-Gen
      term:
        from:
          protocol: bgp
        name: '1'
        then:
          accept: null
  protocols:
    bgp:
      group:
        authentication_key: $9$Y-4JD.PQ9A0ikA0BIrl24aZikmfT3/C
        family:
          inet_vpn:
            unicast: null
        local_address: 192.168.255.13
        log_updown: null
        name: pe1
        neighbor:
          name: 192.168.255.11
        type: internal
    isis:
      interface:
      - name: ge-0/0/3.0
      - name: ge-0/0/4.0
      - name: lo0.0
      level:
        disable: null
        name: '1'
    lldp:
      interface:
        name: all
    mpls:
      interface:
      - name: ge-0/0/3.0
      - name: ge-0/0/4.0
      - disable: null
        name: fxp0.0
    router_advertisement:
      interface:
        name: fxp0.0
    rsvp:
      interface:
      - name: ge-0/0/3.0
      - name: lo0.0
      - name: ge-0/0/4.0
  routing_instances:
    instance:
      instance_type: vrf
      interface:
        name: ge-0/0/9.0
      name: skyrim
      protocols:
        bgp:
          group:
            as_override: null
            family:
              inet:
                unicast: null
            local_as:
              as_number: '65000'
            log_updown: null
            name: skyrim
            neighbor:
              name: 172.20.3.2
              peer_as: '300'
            type: external
      route_distinguisher:
        rd_type: 192.168.100.2:300
      vrf_table_label: null
      vrf_target:
        community: target:300:1
  routing_options:
    autonomous_system:
      as_number: '65000'
    router_id: 192.168.255.13
    static:
      route:
      - name: 10.9.0.0/16
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.101.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.102.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.103.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.104.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
  system:
    host_name: lonestar-pe3
    login:
      user:
        authentication:
          encrypted_password: $6$qHArGlTn$lABpGfi9TdA21rE/NOiumXRK6daKoJMdkrT9eOrmthVRh462VQbAjQs.r0mUP.nE31DTj5kkczpXS0tAmBi880
        class: super-user
        name: automation
        uid: '2000'
    processes:
      dhcp_service:
        traceoptions:
          file:
            filename: dhcp_logfile
            size: 10m
          flag:
            name: packet
          level: all
    root_authentication:
      encrypted_password: $6$tqWrVukX$MONsToHWfROa64jqROzftigejwtwccm1asZ5dbTkb/UCsLNOpF3LZiDY1ltY7Ku2f/XgrstuMblCF43mmi5fe1
    services:
      netconf:
        ssh: null
      ssh:
        root_login: allow
    syslog:
      file:
      - contents:
        - name: any
          notice: null
        - info: null
          name: authorization
        name: messages
      - contents:
          any: null
          name: interactive-commands
        name: interactive-commands
      user:
        contents:
          emergency: null
          name: any
        name: '*'
  version: 20200609.165031.6_builder.r1115480
