site_name: "Juniper SRX Security demo"
site_description: "Build and deploy a full security configuration on vSRX firewalls."
site_url: "https://cdot65.github.io/juniper-srx-security-demo/"
repo_name: "cdot65/juniper-srx-security-demo"
repo_url: "https://github.com/cdot65/juniper-srx-security-demo"
edit_uri: "edit/mainline/site/content"
copyright: "Copyright &copy; 2022 cdot65"
docs_dir: "site/content"
site_dir: "docs"
extra_css:
  - "stylesheets/extra.css"
extra:
  alternate:
    - name: "English"
      link: "./en/"
      lang: "en"

nav:
  - Home: "index.md"
  - Documentation:
      - Overview: "docs/overview.md"
      - Automation:
          - Overview: "docs/automation/overview.md"
          - Scripts:
              - configure.py: "docs/automation/configure.py.md"
              - generate.py: "docs/automation/generate.py.md"
              - rollback.py: "docs/automation/rollback.py.md"
              - validate.py: "docs/automation/validate.py.md"
          - Tools:
              - Dockerfile: "docs/automation/dockerfile.md"
              - Invoke: "docs/automation/invoke.md"
              - Poetry: "docs/automation/poetry.md"
          - Workflow:
              - configure: "docs/automation/configure.md"
              - validate: "docs/automation/validate.md"
      - Network:
          - Overview: "docs/network/overview.md"
          - IP Schema: "docs/network/ip.md"
          - SRX: "docs/network/srx.md"
          - Routing: "docs/network/routing.md"
      - Lab Environment:
          - Juniper vLabs: "docs/lab-environment/juniper-vlabs.md"
          - Local: "docs/lab-environment/local.md"

theme:
  name: "material"
  custom_dir: "site/overrides"
  palette:
    primary: "white"
  font: false
  icon:
    logo: "octicons/terminal-16"
  favicon: "assets/images/favicon.png"
  language: "en"
  features:
    - "tabs"
    - "instant"

markdown_extensions:
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"
  - "pymdownx.tabbed"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - "site/overrides/.icons"

plugins:
  - "search"
  - redirects:
      redirect_maps:
        "docs/juniper-vlabs.md": "docs/lab-environment/juniper-vlabs.md"
        "docs/locally.md": "docs/lab-environment/local.md"
  - macros:
      include_dir: "site/content/docs/include"
