---
base_url: "https://api.mistsys.com/integration"
site: "a16adfef-c5b3-4bfb-b6e7-0ebfedc38e01"
device: "00000000-0000-0000-1000-4c734f096300"
token: "2RksylML2Xo5JzEflzK9B1AkUh0DlRdt6QCfUtlJcO39FGGgLM5tkXb8rxvGaRv79hNxnQujzkxbiQ0ThV0YueJ9Ipr4C9m1"
interface: "ge-0/0/11"
