configuration:
  routing_instances:
    instance:

      # ### VRF VIRTUAL_SWITCH_1: virtual-switch
      - name: "VIRTUAL_SWITCH_1"
        description: "VRF for virtual-switch"
        instance_type: "virtual-switch"

        ### INTERFACES
        # interface:
        #   - name: "xe-0/0/11.0"

        ### PROTOCOLS
        protocols: 
          evpn:
            encapsulation: vxlan
            extended_vni_list:
              - all
            # multicast_mode: ingress-replication
            default_gateway: no-gateway-community

        ### VXLAN
        vtep_source_interface:
          interface_name: "lo0.0"

        ### ROUTE DISTINGUISHERS
        route_distinguisher:
          rd_type: "{{ device.lo0.ipv4 }}:1"

        ### VRF configurations
        # vrf_import:
        #   - IMPORT_GLOBAL

        # vrf_table_label: null

        vrf_target: 
          community: "target:101:1111"
          auto: null

        ### VLANS
        vlans:
          - name: vlan_101
            vlan_id: 101
            l3_interface: irb.101
            vxlan:
              vni: 5101
              ingress_node_replication: null
          - name: vlan_102
            vlan_id: 102
            l3_interface: irb.102
            vxlan:
              vni: 5102
              ingress_node_replication: null
          - name: vlan_103
            vlan_id: 103
            l3_interface: irb.103
            vxlan:
              vni: 5103
              ingress_node_replication: null

      # ### VRF EVPN_VRF_1: vrf
      - name: EVPN_VRF_1
        instance_type: "vrf"

        routing_options:
          router_id: "{{ device.lo1.ipv4 }}"
          autonomous_system: 
            as_number: 64500

        ### INTERFACES
        interface:
          - name: "lo0.1"
          - name: "irb.101"
          - name: "irb.102"
          - name: "irb.103"

        ### ROUTE DISTINGUISHERS
        route_distinguisher:
          rd_type: "{{ device.lo1.ipv4 }}:1"

        ### VRF configurations
        vrf_target: 
          community: "target:64500:1"
