configuration_protocols:
  bgp:
    log_updown: null
    graceful_restart: null
    multipath: null
    group:
      # ### UNDERLAY
      - name: "UNDERLAY"
        export: "( BGP-AOS-Policy || DEFAULT_DENY )"
        type: external
        # family:
        #   inet:
        #     unicast: null
        neighbor:
          - name: "10.2.0.1"
            description: "underlay: dallas-leaf1"
            local_address: "10.2.0.0"
            family:
              inet:
                unicast: null
            peer_as: 65111

          - name: "10.2.0.5"
            description: "underlay: dallas-leaf2"
            local_address: "10.2.0.4"
            family:
              inet:
                unicast: null
            peer_as: 65112

          - name: "10.2.0.9"
            description: "underlay: dallas-leaf3"
            local_address: "10.2.0.8"
            family:
              inet:
                unicast: null
            peer_as: 65113

          - name: "10.2.0.13"
            description: "underlay: dallas-leaf4"
            local_address: "10.2.0.12"
            family:
              inet:
                unicast: null
            peer_as: 65114

        multipath:
          multiple_as: null

      # ### OVERLAY
      - name: "OVERLAY"
        type: external
        multihop:
          ttl: 1
          no_nexthop_change: null
        family:
          evpn:
            signaling: null
            loops: 2
        multipath:
          multiple_as: null
        neighbor:

          - name: "10.2.1.11"
            peer_as: 65111
            description: "overlay: dallas-leaf1"
            local_address: "{{ device.loopback0.ipv4 }}"
            family:
              evpn:
                signaling: null

          - name: "10.2.1.12"
            peer_as: 65112
            description: "overlay: dallas-leaf2"
            local_address: "{{ device.loopback0.ipv4 }}"
            family:
              evpn:
                signaling: null

          - name: "10.2.1.13"
            peer_as: 65113
            description: "overlay: dallas-leaf3"
            local_address: "{{ device.loopback0.ipv4 }}"
            family:
              evpn:
                signaling: null

          - name: "10.2.1.14"
            peer_as: 65114
            description: "overlay: dallas-leaf4"
            local_address: "{{ device.loopback0.ipv4 }}"
            family:
              evpn:
                signaling: null

  lldp:
    interface:
      - name: all
      - name: em0
        disable: null
    port_description_type: interface-alias
    port_id_subtype: interface-name
    neighbour_port_info_display: port-id
