### ---------------------------------------------------------------------------
### JSNAPY TESTS
### ---------------------------------------------------------------------------
- hosts: all
  connection: local
  gather_facts: False
  become: False
  roles: 
    - juniper.junos
  vars:
    provider_info:
      host: "{{ inventory_hostname }}"
      user: "automation"
      passwd: "juniper123"
  tasks:

    # #################################################
    # ### TEST 1: Check Device Alarms               ###
    # #################################################
    - name: "TEST 1 - Check Device Alarms"
      juniper_junos_jsnapy:
        # define remote device parameters
        host: "{{ ansible_host }}"
        user: "{{ provider_info.user }}"
        passwd: "{{ provider_info.passwd }}"

        # define our test file and action
        test_files: tests/alarms.yaml
        action: snapcheck

      # store the output of our test in a new object test1
      register: test_alarms

      # disable failed tests from cancelling the rest of our play
      ignore_errors: True

      # tag the result as test_alarms
      tags: [ test_alarms ]

    - name: "print test_alarms object to screen"
      debug:
        msg: "{{ test_alarms }}"
      # when:
      #   - "test_alarms.passPercentage != 100"

    - name: Check Alarms Test
      assert:
        that:
          - "test_alarms.passPercentage == 100"
      tags: [ test_alarms ]

