configuration:
  '@commit_localtime': 2021-03-25 01:56:39 UTC
  '@commit_seconds': '1616637399'
  '@commit_user': mist
  apply_groups:
  - mist-script
  - top
  groups:
  - event_options:
      event_script:
        file:
        - checksum:
            sha_256: 982a24151d17173695304e221797c3abd44beb8336d13cf15609f48207dfeffc
          name: mist_event_dispatcher.py
          python_script_user: mist
        - checksum:
            sha_256: 0b4df402a20057452cc39f1e8ef9c484aad8fb76a1466564eccc23cd1836e004
          name: mist_link_event_logger.py
          python_script_user: mist
        - checksum:
            sha_256: 2208c79bdbeca7000a860f8c0a6399e8f1d908583bc9cd193ef2ddb8a4cb7a2a
          name: mist_backup_cfg.py
          python_script_user: mist
        - checksum:
            sha_256: b29a60e7228408d8b8ac53047a324f725e09e9c2ba4b282654f03c3b7ddc882e
          name: mist_storm_control_event_logger.py
          python_script_user: mist
        - checksum:
            sha_256: dd94bcab374a467cab5650053fe41134f5f617c32145849e480f5c142ab56ac5
          name: mist_link_event_capturer.py
          python_script_user: mist
        - checksum:
            sha_256: f28019ed90f62be64791ec8a06af2b289e34baed49f191ce7f3cd328ffc09630
          name: mist_monitor_diskspace.py
          python_script_user: mist
        - checksum:
            sha_256: cd4556c1ffd13ad2a457ab801da0bced0b88745af620119ded480c3cda1fb94a
          name: mist_dynamic_port_usages.py
          python_script_user: mist
        - checksum:
            sha_256: 3c9ef50e2288e4bfa21a06a1a5241dd3aa8abb04fffd27e14fe5342df438dde2
          name: mist_dynamic_port_commit.py
          python_script_user: mist
        - checksum:
            sha_256: eeb1573724bba2cd50efb9edffebd8a4f77944dc8de74d7a7f81f9cedef9331a
          name: mist_event_aggregator.py
          python_script_user: mist
        - checksum:
            sha_256: 61253d515a80a2e664e28b3c4eac92dacc3aed16573822e160164ba8b382260f
          name: mist_collect_stats.py
          python_script_user: mist
        - checksum:
            sha_256: f844ac7501828890372059b9b4993d169d4201d3190611337a0eb6abed7b861d
          name: mist_vcsetup_agent.py
          python_script_user: mist
      generate_event:
      - name: get-stats-every-three-minute
        time_interval: '180'
      - name: monitor-diskspace-now
        time_interval: '86400'
      - name: get-perf-probe-stats
        time_interval: '180'
      policy:
      - events:
        - snmp_trap_link_up
        - snmp_trap_link_down
        name: log-on-snmp-trap-link
        then:
          event_script:
            name: mist_event_dispatcher.py
      - events: ui_commit_completed
        name: backup-cfg-after-commit
        then:
          event_script:
            name: mist_event_dispatcher.py
      - events: l2ald_st_ctl_in_effect
        name: log-on-storm-ctrl-in-effect
        then:
          event_script:
            name: mist_storm_control_event_logger.py
      - events:
        - dot1xd_auth_session_deleted
        - dot1xd_rcvd_eaplogof_athntictd
        - dot1xd_usr_access_denied
        - dot1xd_usr_authenticated
        - dot1xd_usr_session_disconnected
        - eswd_stp_state_change_info
        - ui_commit_not_confirmed
        - chassisd_vchassis_member_update_notice
        - chassisd_vchassis_member_list_notice
        - chassisd_vchassis_member_op_notice
        - snmpd_trap_cold_start
        - l2cpd_receive_bpdu_block_enabled
        - chassisd_psu_error
        - chassisd_psu_fan_fail
        - chassisd_psu_input_bad
        - chassisd_psu_overload
        - chassisd_psu_temperature
        - chassisd_psu_voltage
        - jsrpd_ha_control_link_down
        - jsrpd_ha_control_link_up
        - jsrpd_ha_health_weight_low
        - jsrpd_ha_health_weight_recovery
        name: log-on-system-events
        then:
          event_script:
            name: mist_event_dispatcher.py
      - events: monitor-diskspace-now
        name: monitor-diskspace-policy
        then:
          event_script:
            name: mist_monitor_diskspace.py
      - events: get-stats-every-three-minute
        name: get-stats-policy
        then:
          event_script:
            name: mist_event_dispatcher.py
    name: mist-script
    system:
      scripts:
        op:
          file:
          - arguments:
              name: cmd
            checksum:
              sha_256: fffed9f4c538dfee3f98e34302cd30dd2560bd65c9340ff5c3a14cc05f80ec49
            name: mist_helper.py
          - checksum:
              sha_256: b4012cfbaa9ed42b776fa96d016dd9d1036ebe1a5706ede49567db366d5f5e4b
            name: mist_vccmd.py
  - event_options:
      generate_event:
        name: timer-every-one-minute
        time_interval: '60'
      policy:
      - events:
        - lldp_neighbor_up
        - snmp_trap_link_up
        - snmp_trap_link_down
        - ui_commit_completed
        - dot1xd_usr_authenticated
        - get-stats-every-three-minute
        name: dynamic-port-detect
        then:
          event_script:
            name: mist_dynamic_port_usages.py
      - events: timer-every-one-minute
        name: dynamic-port-commit
        then:
          event_script:
            name: mist_dynamic_port_commit.py
    name: mist-dpc
  - forwarding_options:
      storm_control_profiles:
        all: null
        name: default
    name: top
    poe:
      interface:
        name: all
  - interfaces:
      interface:
        name: <*>
        native_vlan_id: '30'
        unit:
          family:
            ethernet_switching:
              interface_mode: trunk
              vlan:
                members: all
          name: '0'
    name: ap
  - interfaces:
      interface:
        name: <*>
        unit:
          family:
            ethernet_switching:
              interface_mode: trunk
              vlan:
                members:
                - Network
                - PC
                - Voice
          name: '0'
    name: trunk
  interfaces:
    interface:
    - name: ge-0/0/0
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/1
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/2
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/3
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/4
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/5
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/6
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/7
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/8
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/9
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/10
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/0/11
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/1/0
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: xe-0/1/0
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: ge-0/1/1
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: xe-0/1/1
      unit:
        family:
          ethernet_switching:
            storm_control:
              profile_name: default
        name: '0'
    - name: irb
      unit:
      - description: default
        name: '0'
      - description: default
        name: '1'
      - description: PC
        name: '10'
      - description: Voice
        name: '20'
      - description: Network
        family:
          inet:
            dhcp:
              client_identifier:
                user_id:
                  ascii: 8403280bd289-30
              force_discover: null
              retransmission_attempt: '60'
              vendor_id: Juniper
        name: '30'
      - description: test
        name: '68'
    - name: vme
      unit:
        family:
          inet:
            address:
              name: 192.168.105.201/24
        name: '0'
    interface_range:
    - apply_groups: ap
      description: connection to mist access points
      member:
        name: ge-0/0/[0-1]
      name: ap
    - apply_groups: trunk
      description: connection to dallas-fw0
      member:
      - name: ge-0/0/3
      - name: ge-0/0/[10-11]
      - name: ge-0/0/[8-9]
      name: trunk
  poe:
    interface:
      disable: null
      name: trunk
  protocols:
    lldp:
      interface:
        name: all
      port_description_type: interface-alias
      port_id_subtype: interface-name
    lldp_med:
      interface:
        name: all
    rstp:
      bpdu_block_on_edge: null
      interface:
      - name: all
      - edge: null
        name: ap
  routing_options:
    static:
      route:
      - name: 192.168.101.0/24
        next_hop: 192.168.105.1
      - name: 192.168.103.0/24
        next_hop: 192.168.105.1
      - name: 192.168.104.0/24
        next_hop: 192.168.105.1
      - name: 10.9.0.0/16
        next_hop: 192.168.105.1
      - name: 0.0.0.0/0
        next_hop: 192.168.105.1
  system:
    authentication_order: password
    auto_snapshot: null
    commit:
      synchronize: null
    host_name: dallas-sw0
    login:
      user:
      - authentication:
          encrypted_password: $6$RzzqIwVZ$K00pQTiMHaI1iHofcOtfqcIllc0EOZ8.YWNM12o7eivn2U/KX50Rfj3HWxSBif8gQ59dALKBq8/3mvsIAT3Kf0
        class: super-user
        name: automation
        uid: '2002'
      - authentication:
          encrypted_password: $6$.d/gaP8W03ofZMCc$XVLFJHdiZsNnuD1HRkganUZN3UV1PVnM0FBpkqIfohFysv5kHLip6QOUbgbsUzuzFo7dIQ9RfDocI3Bg368m10
        class: super-user
        full_name: mist
        name: mist
        uid: '2003'
    name_server:
    - name: 192.168.101.11
    - name: 192.168.101.12
    - name: 1.1.1.1
    processes:
      dhcp_service:
        traceoptions:
          file:
            filename: dhcp_logfile
            size: 10m
          flag:
            name: all
          level: all
    root_authentication:
      encrypted_password: $6$hBobewinmcqt9p.5$HKZ9w/fp0e4Gs6IXKQG1/sHMAbRdbASUVMaDzGqOm5mAxXPQKtzHTn/r4tQwAeC1j/IrZaBs4TUnJubtfWp5U.
    scripts:
      language: python
      synchronize: null
    services:
      netconf:
        rfc_compliant: null
        ssh: null
        yang_compliant: null
      outbound_ssh:
        client:
          device_id: 2324760f-b86d-45ba-80b2-e9c6d9b2f291.8403280bd289
          keep_alive:
            retry: '12'
            timeout: '5'
          name: mist
          secret: $9$uFx20EcleWx7VtuX7Vwg4Fn6AtO1RhrKM5Q6Ap0IRhSrlK8bs2oZUlK4aZGq.IEhyvWN-wY4ax7wg4JDjuOBIylKM8Vs2O1bs2gJZik.5T3n/CBRh/9X7-VY2GDiHqf69AOBECALxNdsYTzF/p0O1RcSeEhSevW-dgoJD.P3690ORF39p0OcSbsY24Zik.f5F-V.P5Q9C8Xx-dsYgoJUj2gQF6/0ORhSlK8-ds4JGreLNbs4oQF39uOSreK8X/CBESyKvWLxNYgoaU.mTGUn/9A0OEcylLxs24oZUsYfTzFAtWLXNdsaJDjk.vWJGUjq.1REcyKMWxNbsW87VY2aJ69Cu0ISyKx7VuOhrvMN-ikqPFnp0B
          servers:
            name: oc-term.mistsys.net
            port: '2200'
            retry: '1000'
            timeout: '60'
          services: netconf
        traceoptions:
          file:
            filename: outbound-ssh.log
            files: '5'
            size: 64k
          flag:
            name: all
      ssh:
        protocol_version: v2
        root_login: allow
    syslog:
      file:
      - archive:
          files: '5'
          size: 2m
        contents:
        - name: any
          notice: null
        - any: null
          name: authorization
        name: messages
      - archive:
          files: '5'
          size: 2m
        contents:
          any: null
          name: interactive-commands
        match: '!(.*mist.*)'
        name: interactive-commands
      - archive:
          files: '5'
          size: 2m
        name: escript.log
      - archive:
          files: '5'
          size: 2m
        name: op-script.log
      - archive:
          files: '5'
          size: 2m
        name: snapshot
      host:
      - contents:
          any: null
          name: any
        name: 192.168.105.80
        port: '5514'
        source_address: 192.168.105.201
        structured_data: null
      - contents:
          any: null
          name: any
        name: 192.168.105.77
        port: '514'
        source_address: 192.168.105.201
        structured_data: null
      user:
        contents:
          emergency: null
          name: any
        name: '*'
    time_zone: UTC
  version: 20200609.165031.6_builder.r1115480
  vlans:
    vlan:
    - l3_interface: irb.30
      name: Network
      vlan_id: '30'
    - name: PC
      vlan_id: '10'
    - name: Voice
      vlan_id: '20'
    - name: default
      vlan_id: '1'
    - name: test
      vlan_id: '68'
