import xmltodict
import json

reply = """
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/21.2R0/junos" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101">
	<zones-information xmlns="http://xml.juniper.net/junos/21.2R0/junos-zones" junos:style="detail">
		<zones-security>
			<zones-security-zonename>
				DMZ_LAB
			</zones-security-zonename>
			<zone-id>
				11
			</zone-id>
			<zones-security-description>
				all lab resources outside of VMware hosts
			</zones-security-description>
			<zones-security-send-reset>
				On
			</zones-security-send-reset>
			<zones-security-policy-configurable>
				Yes
			</zones-security-policy-configurable>
			<zones-security-screen>
				untrust-screen
			</zones-security-screen>
			<zones-security-interfaces-bound>
				3
			</zones-security-interfaces-bound>
			<zones-security-interfaces>
				<zones-security-interface-name>
					ge-0/0/2.201
				</zones-security-interface-name>
				<zones-security-interface-name>
					ge-0/0/2.202
				</zones-security-interface-name>
				<zones-security-interface-name>
					ge-0/0/2.203
				</zones-security-interface-name>
			</zones-security-interfaces>
			<zones-security-advanced-connection-tracking-timeout>
				1800
			</zones-security-advanced-connection-tracking-timeout>
			<zones-security-unidirectional-session-refreshing>
				No
			</zones-security-unidirectional-session-refreshing>
		</zones-security>
		<zones-security>
			<zones-security-zonename>
				HOME
			</zones-security-zonename>
			<zone-id>
				10
			</zone-id>
			<zones-security-description>
				home networks
			</zones-security-description>
			<zones-security-send-reset>
				Off
			</zones-security-send-reset>
			<zones-security-policy-configurable>
				Yes
			</zones-security-policy-configurable>
			<zones-security-interfaces-bound>
				2
			</zones-security-interfaces-bound>
			<zones-security-interfaces>
				<zones-security-interface-name>
					ge-0/0/2.10
				</zones-security-interface-name>
				<zones-security-interface-name>
					st0.0
				</zones-security-interface-name>
			</zones-security-interfaces>
			<zones-security-advanced-connection-tracking-timeout>
				1800
			</zones-security-advanced-connection-tracking-timeout>
			<zones-security-unidirectional-session-refreshing>
				No
			</zones-security-unidirectional-session-refreshing>
		</zones-security>
		<zones-security>
			<zones-security-zonename>
				WAN
			</zones-security-zonename>
			<zone-id>
				13
			</zone-id>
			<zones-security-description>
				public internet via comcast
			</zones-security-description>
			<zones-security-send-reset>
				Off
			</zones-security-send-reset>
			<zones-security-policy-configurable>
				Yes
			</zones-security-policy-configurable>
			<zones-security-screen>
				untrust-screen
			</zones-security-screen>
			<zones-security-interfaces-bound>
				2
			</zones-security-interfaces-bound>
			<zones-security-interfaces>
				<zones-security-interface-name>
					ge-0/0/0.0
				</zones-security-interface-name>
				<zones-security-interface-name>
					ge-0/0/1.0
				</zones-security-interface-name>
			</zones-security-interfaces>
			<zones-security-advanced-connection-tracking-timeout>
				1800
			</zones-security-advanced-connection-tracking-timeout>
			<zones-security-unidirectional-session-refreshing>
				No
			</zones-security-unidirectional-session-refreshing>
		</zones-security>
		<zones-security>
			<zones-security-zonename>
				trust
			</zones-security-zonename>
			<zone-id>
				7
			</zone-id>
			<zones-security-send-reset>
				On
			</zones-security-send-reset>
			<zones-security-policy-configurable>
				Yes
			</zones-security-policy-configurable>
			<zones-security-interfaces-bound>
				0
			</zones-security-interfaces-bound>
			<zones-security-interfaces>
			</zones-security-interfaces>
			<zones-security-advanced-connection-tracking-timeout>
				1800
			</zones-security-advanced-connection-tracking-timeout>
			<zones-security-unidirectional-session-refreshing>
				No
			</zones-security-unidirectional-session-refreshing>
		</zones-security>
		<zones-security>
			<zones-security-zonename>
				untrust
			</zones-security-zonename>
			<zone-id>
				8
			</zone-id>
			<zones-security-send-reset>
				Off
			</zones-security-send-reset>
			<zones-security-policy-configurable>
				Yes
			</zones-security-policy-configurable>
			<zones-security-screen>
				untrust-screen
			</zones-security-screen>
			<zones-security-interfaces-bound>
				0
			</zones-security-interfaces-bound>
			<zones-security-interfaces>
			</zones-security-interfaces>
			<zones-security-advanced-connection-tracking-timeout>
				1800
			</zones-security-advanced-connection-tracking-timeout>
			<zones-security-unidirectional-session-refreshing>
				No
			</zones-security-unidirectional-session-refreshing>
		</zones-security>
		<zones-security>
			<zones-security-zonename>
				junos-host
			</zones-security-zonename>
			<zone-id>
				2
			</zone-id>
			<zones-security-send-reset>
				Off
			</zones-security-send-reset>
			<zones-security-policy-configurable>
				Yes
			</zones-security-policy-configurable>
			<zones-security-interfaces-bound>
				0
			</zones-security-interfaces-bound>
			<zones-security-interfaces>
			</zones-security-interfaces>
			<zones-security-advanced-connection-tracking-timeout>
				1800
			</zones-security-advanced-connection-tracking-timeout>
			<zones-security-unidirectional-session-refreshing>
				No
			</zones-security-unidirectional-session-refreshing>
		</zones-security>
	</zones-information>
</rpc-reply>
"""

# print(xmltodict.parse(reply))

reply_as_dict = xmltodict.parse(reply)
security_zones = reply_as_dict["rpc-reply"]["zones-information"]["zones-security"]

for each in security_zones:
  print(f'{each["zones-security-zonename"]}')

# print(json.dumps(xmltodict.parse(reply)))