image:
  name: registry.gitlab.com/cremsburg/juniper-automation-container

stages:
  - test

run script:
  stage: test
  # dependencies:
  #   - container_setup
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    ANSIBLE_CONFIG: /etc/ansible/ansible.cfg
  script:
    - cd files/ansible
    - cp tests/ansible.cfg ansible.cfg
    - echo 'Ansible refuses to read from a world-writeable folder, hence' && chmod -v 700 $(pwd)
    - ansible --version
    - ansible-playbook pb.configuration.build.yaml -i inventory.yaml
  allow_failure: true
  # when: manual
