configuration:
  '@commit_localtime': 2021-03-29 09:45:38 CDT
  '@commit_seconds': '1617029138'
  '@commit_user': root
  chassis:
    aggregated_devices:
      ethernet:
        device_count: '64'
  groups:
  - interfaces:
      interface:
        name: irb
        unit:
          family:
            inet:
              address:
                name: <*>
                preferred: null
                primary: null
          name: <*>
          proxy_macip_advertisement: null
          virtual_gateway_accept_data: null
          virtual_gateway_v4_mac: 00:5e:5e:5e:00:01
    name: IRB_OPTIONS
  - interfaces:
      interface:
        mtu: '9192'
        name: <*>
    name: AE_MTU_JUMBO
  - interfaces:
      interface:
        aggregated_ether_options:
          lacp:
            active: null
            periodic: slow
        name: <*>
    name: AE_LACP_BOND
  interfaces:
    interface:
    - description: '[xe-0/0/0] to dc1-leaf1'
      name: xe-0/0/0
      unit:
        family:
          inet:
            address:
              name: 172.16.1.0/31
        name: '0'
    - description: '[xe-0/0/1] to dc1-leaf2'
      name: xe-0/0/1
      unit:
        family:
          inet:
            address:
              name: 172.16.1.2/31
        name: '0'
    - description: '[xe-0/0/2] to dc1-leaf3'
      name: xe-0/0/2
      unit:
        family:
          inet:
            address:
              name: 172.16.1.4/31
        name: '0'
    - description: '[xe-0/0/3] to dc1-leaf4'
      name: xe-0/0/3
      unit:
        family:
          inet:
            address:
              name: 172.16.1.6/31
        name: '0'
    - name: em0
      unit:
        description: out of band interface
        family:
          inet:
            address:
              name: 192.168.105.11/24
        name: '0'
    - name: em1
      unit:
        family:
          inet:
            address:
              name: 169.254.0.2/24
        name: '0'
    - apply_groups: IRB_OPTIONS
      name: irb
      unit:
      - family:
          inet:
            address:
              name: 10.10.0.11/24
              virtual_gateway_address: 10.10.0.1
        name: '100'
      - family:
          inet:
            address:
              name: 10.20.0.11/24
              virtual_gateway_address: 10.20.0.1
        name: '200'
      - family:
          inet:
            address:
              name: 10.30.0.11/24
              virtual_gateway_address: 10.30.0.1
        name: '300'
      - family:
          inet:
            address:
              name: 10.40.0.11/24
              virtual_gateway_address: 10.40.0.1
        name: '400'
    - name: lo0
      unit:
      - description: underlay loopback
        family:
          inet:
            address:
              name: 192.168.0.1/32
              primary: null
        name: '0'
      - description: overlay loopback 1
        family:
          inet:
            address:
              name: 192.168.0.101/32
        name: '1'
  policy_options:
    policy_statement:
    - name: BGP_LOOPBACK0
      term:
        from:
          protocol: direct
          route_filter:
            address: 192.168.0.1/32
            exact: null
        name: TERM1
        then:
          accept: null
    - name: PFE_ECMP
      term:
        name: LOAD_BALANCE
        then:
          accept: null
          load_balance:
            per_packet: null
  protocols:
    bgp:
      group:
      - export: BGP_LOOPBACK0
        family:
          inet:
            unicast: null
        hold_time: '10'
        local_as:
          as_number: '65001'
        multipath:
          multiple_as: null
        name: UNDERLAY
        neighbor:
        - description: 'underlay: dc1-leaf1'
          name: 172.16.1.1
          peer_as: '65011'
        - description: 'underlay: dc1-leaf2'
          name: 172.16.1.3
          peer_as: '65012'
        - description: 'underlay: dc1-leaf3'
          name: 172.16.1.5
          peer_as: '65013'
        - description: 'underlay: dc1-leaf4'
          name: 172.16.1.7
          peer_as: '65014'
        type: external
      - family:
          evpn:
            signaling: null
        local_address: 192.168.0.1
        name: OVERLAY
        neighbor:
        - description: 'overlay: dc1-leaf1'
          name: 192.168.1.11
        - description: 'overlay: dc1-leaf2'
          name: 192.168.1.12
        - description: 'overlay: dc1-leaf3'
          name: 192.168.1.13
        - description: 'overlay: dc1-leaf4'
          name: 192.168.1.14
        type: internal
      - family:
          evpn:
            signaling: null
        local_address: 192.168.0.1
        name: OVERLAY_RR_MESH
        neighbor:
          description: 'route-reflector: dc1-spine2'
          name: 192.168.0.2
        type: internal
    evpn:
      default_gateway: no-gateway-community
      encapsulation: vxlan
      extended_vni_list: all
    lldp:
      interface:
      - name: all
      - disable: null
        name: em0
      port_description_type: interface-alias
      port_id_subtype: interface-name
  routing_instances:
    instance:
      instance_type: vrf
      interface:
      - name: irb.100
      - name: irb.200
      - name: lo0.1
      name: VRF_1
      route_distinguisher:
        rd_type: 192.168.0.101:1
      routing_options:
        auto_export: null
        router_id: 192.168.0.101
      vrf_target:
        community: target:10001:1
  routing_options:
    autonomous_system:
      as_number: '65100'
    forwarding_table:
      ecmp_fast_reroute: null
      export: PFE_ECMP
    router_id: 192.168.0.1
    static:
      route:
      - name: 10.9.0.0/17
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.101.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.102.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.103.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.104.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
  snmp:
    community:
      authorization: read-only
      clients:
        name: 0.0.0.0/0
      name: healthbot
    interface: em0.0
    trap_group:
      categories:
        chassis: null
        routing: null
      name: healthbot
      targets:
        name: 192.168.105.77
      version: v2
    trap_options:
      source_address:
        address: 192.168.105.11
  switch_options:
    route_distinguisher:
      rd_type: 192.168.0.1:1
    vrf_target:
      auto: null
      community: target:65100:1111
    vtep_source_interface:
      interface_name: lo0.0
  system:
    host_name: dallas-spine1
    login:
      user:
        authentication:
          encrypted_password: $6$ZlA2peEY$803k5QuDxH1YBoHBVObfr0KVLavXLTu8nUlzIUmJbIhrMcQZZ3dWLD7Jj.IK0RKFXMJ6Csf2pnxg8MiuppZHj1
        class: super-user
        name: automation
        uid: '3001'
    name_server:
    - name: 192.168.101.11
    - name: 192.168.101.12
    root_authentication:
      encrypted_password: $6$eG4FXiQW$J4/a.5GZlXlrKcvJTpbaMl.qIelPqjR5lFk.POmxo5O3Vp5OdjHFFJ97PMqvABuZZOGXrdvSE6YF3f33wilgO.
    services:
      extension_service:
        notification:
          allow_clients:
            address: 0.0.0.0/0
        request_response:
          grpc:
            max_connections: '30'
            undocumented:
            - clear_text: null
            - skip_authentication: null
      netconf:
        ssh: null
      rest:
        enable_explorer: null
        http:
          port: '8080'
      ssh:
        root_login: allow
    syslog:
      file:
      - contents:
        - name: any
          notice: null
        - info: null
          name: authorization
        name: messages
      - contents:
          any: null
          name: interactive-commands
        name: interactive-commands
      - contents:
          info: null
          name: any
        match: (requested 'commit' operation)|(requested 'commit synchronize' operation)|(copying configuration to juniper.save)|(commit complete)|ifAdminStatus|(FRU power)|(FRU removal)|(FRU insertion)|(link UP)|transitioned|Transferred|transfer-file|(license add)|(license delete)|(package -X update)|(package -X delete)|(FRU Online)|(FRU Offline)|(plugged in)|(unplugged)|GRES
        name: default-log-messages
        structured_data: null
      host:
      - contents:
          any: null
          name: any
        name: 192.168.105.80
        port: '5514'
        source_address: 192.168.105.11
        structured_data: null
      - contents:
          any: null
          name: any
        name: 192.168.105.77
        port: '514'
        source_address: 192.168.105.11
        structured_data: null
      user:
        contents:
          emergency: null
          name: any
        name: '*'
    time_zone: America/Chicago
  version: 20191212.201431_builder.r1074901
  vlans:
    vlan:
    - description: data network
      l3_interface: irb.100
      name: VNI_10000
      vlan_id: '100'
      vxlan:
        vni: '10000'
    - description: voice network
      l3_interface: irb.200
      name: VNI_20000
      vlan_id: '200'
      vxlan:
        vni: '20000'
    - description: guest network
      l3_interface: irb.300
      name: VNI_30000
      vlan_id: '300'
      vxlan:
        vni: '30000'
    - description: oob network
      l3_interface: irb.400
      name: VNI_40000
      vlan_id: '400'
      vxlan:
        vni: '40000'
