---
  ### ---------------------------------------------------------------------------
  ### CREATE AN SDWAN SITE IN CSO
  ### ---------------------------------------------------------------------------
  - hosts: localhost
    connection: local
    gather_facts: False
    become: False
    any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
    roles:
      ### ---------------------------------------------------------------------------
      ### CSO SD-WAN work 
      ### ---------------------------------------------------------------------------
      - { role: cso_auth }
      - { role: cso_get_sites }
