### ---------------------------------------------------------------------------
### JSNAPY TESTS
### ---------------------------------------------------------------------------
- hosts: all
  connection: local
  gather_facts: False
  become: False
  roles: 
    - juniper.junos
  vars:
    provider_info:
      host: "{{ inventory_hostname }}"
      user: "automation"
      passwd: "juniper123"
  tasks:

    # #################################################
    # ### Check Firewall Policy Counters            ###
    # #################################################
    - name: "### CHECK FIREWALL POLICIES"
      juniper_junos_jsnapy:
        # define remote device parameters
        host: "{{ ansible_host }}"
        user: "{{ provider_info.user }}"
        passwd: "{{ provider_info.passwd }}"

        # define our test file and action
        test_files: tests/firewall.yaml
        action: snapcheck

      # store the output of our test in a new object test_firewall
      register: test_firewall

      # disable failed tests from cancelling the rest of our play
      ignore_errors: True

      # tag the result as test_firewall
      tags: [ test_firewall ]

    - name: "print test_firewall object to screen"
      debug:
        msg: "{{ test_firewall }}"
      when:
        - "test_firewall.passPercentage != 100"

    - name: Check Firewall Counter Test
      assert:
        that:
          - "test_firewall.passPercentage == 100"
      tags: [ test_firewall ]
