configuration:
  '@commit_localtime': 2021-03-28 23:48:32 UTC
  '@commit_seconds': '1616975312'
  '@commit_user': root
  interfaces:
    interface:
    - disable: null
      name: ge-0/0/0
    - name: ge-0/0/1
      unit:
        family:
          inet:
            address:
              name: 10.1.11.11/24
          iso: null
          mpls: null
        name: '0'
    - name: ge-0/0/2
      unit:
        family:
          inet:
            address:
              name: 10.2.11.11/24
          iso: null
          mpls: null
        name: '0'
    - disable: null
      name: ge-0/0/3
    - disable: null
      name: ge-0/0/4
    - disable: null
      name: ge-0/0/5
    - disable: null
      name: ge-0/0/6
    - disable: null
      name: ge-0/0/7
    - disable: null
      name: ge-0/0/8
    - name: ge-0/0/9
      unit:
        family:
          inet:
            address:
              name: 172.20.1.1/24
        name: '0'
    - name: fxp0
      unit:
        family:
          inet:
            address:
              name: 192.168.105.25/24
        name: '0'
    - name: lo0
      unit:
        family:
          inet:
            address:
              name: 192.168.255.11/32
          iso:
            address:
              name: 49.0001.0192.0168.0255.0011.00
        name: '0'
  protocols:
    bgp:
      group:
        authentication_key: $9$TF6ABIcvWxp0WxNdg4QFn/p01RhrKM
        family:
          inet_vpn:
            unicast: null
        local_address: 192.168.255.11
        log_updown: null
        name: pe3
        neighbor:
          name: 192.168.255.13
        type: internal
    isis:
      interface:
      - name: ge-0/0/1.0
      - name: ge-0/0/2.0
      - name: lo0.0
      level:
        disable: null
        name: '1'
    lldp:
      interface:
        name: all
    mpls:
      interface:
      - disable: null
        name: fxp0.0
      - name: ge-0/0/1.0
      - name: ge-0/0/2.0
      label_switched_path:
        bandwidth:
          per_traffic_class_bandwidth: 100m
        name: LSP-TO-PE3
        primary:
          name: VIA-P2
        to: 192.168.255.13
      path:
        name: VIA-P2
        path_list:
          loose: null
          name: 10.1.2.2
    router_advertisement:
      interface:
        name: fxp0.0
    rsvp:
      interface:
      - name: ge-0/0/1.0
      - name: ge-0/0/2.0
      - name: lo0.0
  routing_instances:
    instance:
      instance_type: vrf
      interface:
        name: ge-0/0/9.0
      name: skyrim
      protocols:
        bgp:
          group:
            as_override: null
            family:
              inet:
                unicast: null
            local_as:
              as_number: '65000'
            log_updown: null
            name: skyrim
            neighbor:
              name: 172.20.1.2
              peer_as: '300'
            type: external
      route_distinguisher:
        rd_type: 192.168.100.1:300
      vrf_table_label: null
      vrf_target:
        community: target:300:1
  routing_options:
    autonomous_system:
      as_number: '65000'
    router_id: 192.168.255.11
    static:
      route:
      - name: 192.168.101.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.102.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.103.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 192.168.104.0/24
        next_hop: 192.168.105.1
        no_readvertise: null
      - name: 10.9.0.0/16
        next_hop: 192.168.105.1
        no_readvertise: null
  system:
    host_name: lonestar-pe1
    login:
      user:
        authentication:
          encrypted_password: $6$vgLbhHaz$VAqRz/KEh3jdTgCalqu0UHFyqxMgnLKaQsBCU9ATX1rnCzi02wGPmwTabHc3DumKLz9JgwF150XD28YlEhUkz1
        class: super-user
        name: automation
        uid: '2000'
    processes:
      dhcp_service:
        traceoptions:
          file:
            filename: dhcp_logfile
            size: 10m
          flag:
            name: packet
          level: all
    root_authentication:
      encrypted_password: $6$5iPFnMdx$GwuxuRpwCGGydmaO8LKaffdxUfGBUMXdKFJ1f2V8XcBMQNWGDW4m1ewjddAsx9NL7SBuAJ1poWxggT2Drab0j1
    services:
      extension_service:
        notification:
          allow_clients:
            address: 0.0.0.0/0
        request_response:
          grpc:
            max_connections: '30'
            undocumented:
            - clear_text: null
            - skip_authentication: null
      netconf:
        ssh: null
      ssh:
        root_login: allow
    syslog:
      file:
      - contents:
        - name: any
          notice: null
        - info: null
          name: authorization
        name: messages
      - contents:
          any: null
          name: interactive-commands
        name: interactive-commands
      user:
        contents:
          emergency: null
          name: any
        name: '*'
  version: 20200609.165031.6_builder.r1115480
