# Generated by Django 3.1.7 on 2021-03-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_backup_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='text',
            new_name='config_json',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='config',
        ),
        migrations.AddField(
            model_name='backup',
            name='config_set',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='config_text',
            field=models.TextField(blank=True),
        ),
    ]
