configuration:
  '@commit_localtime': 2020-12-19 02:08:04 UTC
  '@commit_seconds': '1608343684'
  '@commit_user': root
  chassis:
    aggregated_devices:
      ethernet:
        device_count: '2'
  interfaces:
    interface:
    - description: lonestar-br0-fw0
      mtu: '9000'
      name: ge-0/0/0
      unit:
        family:
          inet:
            address:
              name: 216.227.251.0/31
          mpls: null
        name: '0'
    - description: endor
      name: ge-0/0/7
      unit:
        family:
          inet:
            address:
              name: 42.72.106.0/31
        name: '0'
    - mtu: '9000'
      name: ge-0/1/0
    - mtu: '9000'
      name: ge-0/1/1
    - mtu: '9000'
      name: ge-0/1/2
      unit:
        family:
          inet:
            address:
              name: 74.51.192.0/31
          mpls: null
        name: '0'
    - mtu: '9000'
      name: ge-0/1/3
      unit:
        family:
          inet:
            address:
              name: 190.221.165.0/31
          mpls: null
        name: '0'
    - name: fxp0
      unit:
        family:
          inet:
            address:
              name: 192.168.105.230/24
        name: '0'
    - mtu: '9000'
      name: irb
      unit:
        family:
          inet:
            address:
              name: 74.51.192.0/31
        name: '100'
    - name: lo0
      unit:
        family:
          inet:
            address:
            - name: 127.0.0.1/32
            - name: 192.168.255.230/32
        name: '0'
  protocols:
    ldp:
      interface:
      - name: ge-0/0/0.0
      - name: ge-0/1/2.0
      - name: ge-0/1/3.0
      - name: all
    lldp:
      interface:
        name: all
    mpls:
      interface:
      - name: all
      - name: ge-0/1/3.0
      - name: ge-0/0/0.0
      - name: ge-0/1/2.0
    ospf:
      area:
        interface:
        - name: lo0.0
          passive: null
        - interface_type: p2p
          name: ge-0/0/0.0
        - interface_type: p2p
          name: ge-0/1/2.0
        - interface_type: p2p
          name: ge-0/1/3.0
        name: 0.0.0.0
  routing_options:
    static:
      route:
        name: 0.0.0.0/0
        next_hop: 192.168.105.1
  system:
    host_name: colo-rt0
    login:
      user:
        authentication:
          encrypted_password: $6$QwA7mzPH$TQqHPy.49vbfYqOvLoimAreZkeIFbqmxh1sf6pU3YjZ00eB4RFkiQDTdR.riOkGETFWTckNHydckQxSjKjQ0k1
        class: super-user
        name: automation
        uid: '2000'
    root_authentication:
      encrypted_password: $6$qqxM8XXC$Lk5av9u90ktPoTV8OJ0JH7SlQ4dHqlGI1MUS6etRl.XnnMIQ99gAK5Wgs2DlW0JaAU5zHgkizUAAl/aTt5bxB0
    services:
      netconf:
        ssh: null
      ssh:
        root_login: allow
    syslog:
      file:
        contents:
        - name: any
          notice: null
        - info: null
          name: authorization
        name: messages
      user:
        contents:
          emergency: null
          name: any
        name: '*'
  version: 20.4R1.12
