yangDir = "/home/cdot/dev/juniper-terraform-srx/files/terraform/build/ex/interfaces"
providerDir = "/home/cdot/dev/juniper-terraform-srx/files/terraform/build/ex/interfaces/provider"
xpathPath = "/home/cdot/dev/juniper-terraform-srx/files/terraform/build/ex/interfaces/xpath_test.xml"
fileType = "both"
providerName = "interfaces"
